# the following values must be set in https://travis-ci.com/<github-repo>/settings
# - DOCKER_REPO (eg. myrepo/myapp)
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

# xenial is required to run "multiarch/qemu-user-static -p yes"
dist: xenial
language: minimal
services: docker
os: linux

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

env:
  - ARCH=amd64
  - ARCH=arm32v6
  - ARCH=arm32v7
  - ARCH=arm64v8
  - ARCH=i386
  - ARCH=ppc64le
  - ARCH=s390x

install:
  # the experimental flag for the docker cli is required to use docker manifest commands
  - mkdir -p ${HOME}/.docker
  - echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json
  - sudo systemctl restart docker

script:
  # build and test an image with the provided ARCH
  - make build ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}

after_success:
  # make manifest will fail by design until all images are present on the docker repo
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - make push ARCH=${ARCH} DOCKER_REPO=${DOCKER_REPO}
  - make manifest DOCKER_REPO=${DOCKER_REPO}