name: build

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        run: make build DOCKER_REPO=${{ secrets.DOCKER_REPO }}

      - name: login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: manifest
        run: make manifest DOCKER_REPO=${{ secrets.DOCKER_REPO }}
