name: deploy

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: curl -fsSL get.docker.com | sh
        
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        run: make build DOCKER_REPO=${{ secrets.DOCKER_REPO }}

      - name: login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: buildx
        run: make buildx DOCKER_REPO=${{ secrets.DOCKER_REPO }} BUILD_OPTIONS=--push
      
      - name: inspect
        run: make inspect DOCKER_REPO=${{ secrets.DOCKER_REPO }}
