name: deploy

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  job-01:
    runs-on: ubuntu-latest

    steps:
      - name: install docker
        run: curl -fsSL get.docker.com | sh

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: checkout source
        uses: actions/checkout@v1

      - name: build on the host architecture
        run: make build DOCKER_REPO=${{ secrets.DOCKER_REPO }}
      
      - name: test on the host architecture
        run: make test DOCKER_REPO=${{ secrets.DOCKER_REPO }}

      - name: cross-build multiarch manifest
        run: make all DOCKER_REPO=${{ secrets.DOCKER_REPO }} EXTRA_OPTS=--push
