name: deploy

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  DOCKER_REPO:
    runs-on: ubuntu-latest

    steps:
      - name: docker install
        run: curl -fsSL get.docker.com | sh

      - name: source checkout
        uses: actions/checkout@v1

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: manifest build
        run: make buildx DOCKER_REPO=${{ secrets.DOCKER_REPO }} EXTRA_OPTS="--push --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/arm/v6"
