name: deploy

on:
  push:
    branches:
    - master
    - /^v\d+\.\d+\.\d+.*$/

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCH: [amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x]

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: build
      run: make build ARCH=${{ matrix.ARCH }} DOCKER_REPO=${{ secrets.DOCKER_REPO }}

    - name: push
      run: make push ARCH=${{ matrix.ARCH }} DOCKER_REPO=${{ secrets.DOCKER_REPO }}

  manifest:
    needs: push

    runs-on: ubuntu-latest

    steps:

    - name: config
      run: |
        mkdir -p ${HOME}/.docker
        echo '{"experimental":"enabled"}' | tee ${HOME}/.docker/config.json
        sudo systemctl restart docker
    
    - name: checkout
      uses: actions/checkout@v1

    - name: manifest
      run: make manifest DOCKER_REPO=${{ secrets.DOCKER_REPO }}
