name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: curl -fsSL get.docker.com | sh
        
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        run: make build

      - name: buildx
        run: make buildx