name: test

on:
  pull_request:

jobs:
  PLATFORM:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        PLATFORM: [linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/arm/v6]

    steps:
      - name: docker install
        run: curl -fsSL get.docker.com | sh

      - name: source checkout
        uses: actions/checkout@v1

      - name: platform build
        run: make build EXTRA_OPTS=--platform=${{ matrix.PLATFORM }}

      - name: platform test
        run: make test EXTRA_OPTS=--platform=${{ matrix.PLATFORM }}