name: test

on:
  pull_request:

jobs:
  job-01:
    runs-on: ubuntu-latest

    steps:
      - name: install docker
        run: curl -fsSL get.docker.com | sh
        
      - name: checkout source
        uses: actions/checkout@v1

      - name: build and test
        run: make build

      - name: build all
        run: make all